# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNInLocoEngageSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNInLocoEngageSample

  pod 'InLocoEngage-iOS-SDK', '~> 4.0.0'
  pod 'InLocoMedia-iOS-SDK/Location', '~> 4.0.0'
  pod 'Firebase/Core', '~> 4.11.0'
  pod 'Firebase/Messaging', '~> 4.11.0'


  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end